# Generated by Django 3.1.4 on 2021-01-01 13:57

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', phone_field.models.PhoneField(max_length=31)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
