# Generated by Django 3.1.4 on 2021-01-01 16:57

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210101_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
